In [0]:
from google.colab import drive
drive.mount('/gdrive')
import os
os.chdir("/gdrive/My Drive/CS5412/data")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
import datetime
import pandas as pd
import os
import numpy as np

In [0]:
# construct 260 * 7 * 24 cnt and total fare
# row is time column is (district id - 1)

# cnt = np.zeros((7*24, 263))
# total_fare = np.zeros((7*24, 263))
# print(cnt.dtype)

In [0]:
# As we have the cnt, we can load from file
def load_cnt_fare(file, start, end, cnt_file, total_fare_file):
  df = pd.read_csv(file)
  cnt = np.zeros((7*24, 263))
  total_fare = np.zeros((7*24, 263))
  
  for index, row in df.iterrows():
    if index % 100000 == 0:
      print(index, df.shape[0])
    
    pickup_datetime = datetime.datetime.strptime(row['tpep_pickup_datetime'], '%Y-%m-%d %H:%M:%S')
    dropoff_datetime = datetime.datetime.strptime(row['tpep_dropoff_datetime'], '%Y-%m-%d %H:%M:%S')
    
    if row['tpep_pickup_datetime'] >= start and row['tpep_pickup_datetime'] < end and int(row['PULocationID']) <= 263 and int(row['DOLocationID']) <= 263:
#       if (pickup_datetime - datetime.datetime.strptime('2019-01-01', '%Y-%m-%d')).days % 2 == 0:
      row_num = pickup_datetime.weekday() * 24 + pickup_datetime.hour
      col_num = int(row['PULocationID']) - 1
      cnt[row_num][col_num] += 1
      total_fare[row_num][col_num] += float(row['total_amount'])
  np.save(cnt_file, cnt)
  np.save(total_fare_file, total_fare)  

In [0]:
cab_data = [
    "yellow_tripdata_2018-01.csv",
    "yellow_tripdata_2018-02.csv",
    "yellow_tripdata_2018-03.csv",
    "yellow_tripdata_2018-04.csv",
    "yellow_tripdata_2018-05.csv",
    "yellow_tripdata_2018-06.csv",
    "yellow_tripdata_2018-07.csv",
    "yellow_tripdata_2018-08.csv",
    "yellow_tripdata_2018-09.csv",
    "yellow_tripdata_2018-10.csv",
    "yellow_tripdata_2018-11.csv",
    "yellow_tripdata_2018-12.csv"
]

# cab_data = [
#     "yellow_tripdata_2018-01.csv"
# ]

start_time = [
    "2018-01-01 00:00:00",
    "2018-02-01 00:00:00",
    "2018-03-01 00:00:00",
    "2018-04-01 00:00:00",
    "2018-05-01 00:00:00",
    "2018-06-01 00:00:00",
    "2018-07-01 00:00:00",
    "2018-08-01 00:00:00",
    "2018-09-01 00:00:00",
    "2018-10-01 00:00:00",
    "2018-11-01 00:00:00",
    "2018-12-01 00:00:00"
]

# start_time = [
#     "2018-01-01 00:00:00"
# ]

end_time = [
    "2018-02-01 00:00:00",
    "2018-03-01 00:00:00",
    "2018-04-01 00:00:00",
    "2018-05-01 00:00:00",
    "2018-06-01 00:00:00",
    "2018-07-01 00:00:00",
    "2018-08-01 00:00:00",
    "2018-09-01 00:00:00",
    "2018-10-01 00:00:00",
    "2018-11-01 00:00:00",
    "2018-12-01 00:00:00",
    "2019-01-01 00:00:00"
]

# end_time = [
#     "2018-02-01 00:00:00"
# ]

cnt_files = [
    "2017-01-cnt.npy",
    "2017-02-cnt.npy",
    "2017-03-cnt.npy",
    "2017-04-cnt.npy",
    "2017-05-cnt.npy",
    "2017-06-cnt.npy",
    "2017-07-cnt.npy",
    "2017-08-cnt.npy",
    "2017-09-cnt.npy",
    "2017-10-cnt.npy",
    "2017-11-cnt.npy",
    "2017-12-cnt.npy"
]

total_fare_files = [
    "2017-01-total-fare.npy",
    "2017-02-total-fare.npy",
    "2017-03-total-fare.npy",
    "2017-04-total-fare.npy",
    "2017-05-total-fare.npy",
    "2017-06-total-fare.npy",
    "2017-07-total-fare.npy",
    "2017-08-total-fare.npy",
    "2017-09-total-fare.npy",
    "2017-10-total-fare.npy",
    "2017-11-total-fare.npy",
    "2017-12-total-fare.npy"
]

In [0]:
for i in range(len(cab_data)):
  print("Month: ", i + 1)
  load_cnt_fare(cab_data[i], start_time[i], end_time[i], cnt_files[i], total_fare_files[i])

Month:  1
0 9710124
100000 9710124
200000 9710124
300000 9710124
400000 9710124
500000 9710124
600000 9710124
700000 9710124
800000 9710124
900000 9710124
1000000 9710124
1100000 9710124
1200000 9710124
1300000 9710124
1400000 9710124
1500000 9710124
1600000 9710124
1700000 9710124
1800000 9710124
1900000 9710124
2000000 9710124
2100000 9710124
2200000 9710124
2300000 9710124
2400000 9710124
2500000 9710124
2600000 9710124
2700000 9710124
2800000 9710124
2900000 9710124
3000000 9710124
3100000 9710124
3200000 9710124
3300000 9710124
3400000 9710124
3500000 9710124
3600000 9710124
3700000 9710124
3800000 9710124
3900000 9710124
4000000 9710124
4100000 9710124
4200000 9710124
4300000 9710124
4400000 9710124
4500000 9710124
4600000 9710124
4700000 9710124
4800000 9710124
4900000 9710124
5000000 9710124
5100000 9710124
5200000 9710124
5300000 9710124
5400000 9710124
5500000 9710124
5600000 9710124
5700000 9710124
5800000 9710124
5900000 9710124
6000000 9710124
6100000 9710124
6200000 97101

In [0]:
print(cnt)
print("-------")
print(total_fare)

[[1.000e+00 0.000e+00 3.000e+00 ... 3.807e+03 4.480e+03 2.760e+02]
 [3.000e+00 0.000e+00 4.000e+00 ... 2.557e+03 2.809e+03 2.470e+02]
 [7.000e+00 0.000e+00 2.000e+00 ... 1.792e+03 1.859e+03 1.720e+02]
 ...
 [2.200e+01 0.000e+00 9.000e+00 ... 9.858e+03 9.508e+03 3.570e+02]
 [1.300e+01 0.000e+00 4.000e+00 ... 7.692e+03 8.020e+03 3.350e+02]
 [3.000e+00 0.000e+00 9.000e+00 ... 5.120e+03 6.172e+03 3.020e+02]]
-------
[[7.5600000e+00 0.0000000e+00 8.5220000e+01 ... 4.8304100e+04
  9.2756000e+04 2.4900140e+04]
 [3.7740000e+02 0.0000000e+00 5.6700000e+01 ... 3.3059260e+04
  5.4646890e+04 2.0156580e+04]
 [5.7850000e+02 0.0000000e+00 9.1860000e+01 ... 2.2380550e+04
  3.4412290e+04 1.5919930e+04]
 ...
 [2.0658000e+03 0.0000000e+00 2.5473000e+02 ... 1.1575301e+05
  1.6971503e+05 3.3145160e+04]
 [1.1707300e+03 0.0000000e+00 6.0550000e+01 ... 9.3388310e+04
  1.5424941e+05 3.3584550e+04]
 [3.2141000e+02 0.0000000e+00 4.5367000e+02 ... 6.5315200e+04
  1.2814179e+05 2.6651440e+04]]


In [0]:
fare = total_fare / cnt
print(fare)

[[  7.56                nan  28.40666667 ...  12.6882322   20.70446429
   90.21789855]
 [125.8                 nan  14.175      ...  12.92892452  19.45421502
   81.60558704]
 [ 82.64285714          nan  45.93       ...  12.48914621  18.51118343
   92.55773256]
 ...
 [ 93.9                 nan  28.30333333 ...  11.74203794  17.84970867
   92.84358543]
 [ 90.05615385          nan  15.1375     ...  12.14096594  19.23309352
  100.25238806]
 [107.13666667          nan  50.40777778 ...  12.756875    20.76179358
   88.24980132]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [0]:
fare[np.isnan(fare)] = 0
max_profit_id = np.argmax(fare, axis=1) + 1
max_profit = np.max(fare, axis=1)
print(max_profit_id)
print(max_profit)
print(max_profit_id.shape)
print(cnt)

[154 117   5  60  11  64 206 154 154   1  23  23 117 176   6 120  44 204
 117 154  99 156 117 184  31  45 117 108  67  64   1 172  86   6   1   1
  57  44  84   2 253 154 187 265 221 253 176 184 252  71 252  11 118  44
   1  27   1 251 187 253 184 154 206 206 156 154 184 253 251 154 206  23
 253 213  19 176 124  28 253 176 176  23  27 154 154 154 206 251 120 117
 156 156 204   5 156 204   9   1  19 156 109 108   1 176   1   1 154 221
   6  23 154 253 245 154 265 154   5 149 154 208   1   1  63 178  23 206
 124   1 154 201   1 156 176 115 251 258   5 117   1 122 154 123   1 175
   1   1  64 201 219 253 253 154 253  46   1 156 214 187   6 117   1 115
   1 253 154 156 184 222]
[  146.12333333   266.56         120.96          99.92
    91.8          141.07          85.12         101.51333333
   119.465         93.03444444   124.97333333   114.98
   490.96         120.96         189.32         253.56
   152.8          130.34         176.51333333   200.32
   115.32         155.8          169

In [0]:
# store fare
# np.save("2018-fare.npy", fare)
np.save("2018-01-cnt.npy", cnt)
np.save("2018-01-total-fare.npy", total_fare)

# We need to evaluate our model

In [0]:
test_profit_original = 0.0
prev = ("2018-07-01 00:00:00", 100)
# for i in range(265):
#   heappush(heap_original, ("2018-01-00 00:00:00", i + 1, i + 1)) 
# The first element is the last time drop off # The second element is the last time drop off location id and third element is the first time pick up id

In [0]:
def original(file, start, end, log_file):
  global prev, test_profit_original
  df = pd.read_csv(file)
  print("data loaded")
  df = df[(df.tpep_pickup_datetime >= start) & (df.tpep_pickup_datetime < end)]
  
  df = df[(df.PULocationID < 264) & (df.DOLocationID < 264)]
  df = df.sort_values(by=['tpep_pickup_datetime'])
  
  with open(log_file, "a+") as f:
    while True:
      ele = prev
      f.write(str(ele))
      f.write(" ")
      f.write(str(test_profit_original))
      f.write("\n")
      df_filter = df[(df.tpep_pickup_datetime > ele[0]) & (df.PULocationID == ele[1])].reset_index()
      if df_filter.shape[0] == 0:
        prev = ele
        break
  #     print(df_filter.loc[0])
  #     print(df_filter.iloc[0])
      new_ele = (df_filter.iloc[0]['tpep_dropoff_datetime'], df_filter.iloc[0]['DOLocationID'])
      test_profit_original += float(df_filter.iloc[0]['total_amount'])
      prev = new_ele  

In [0]:
for i in range(len(cab_data)):
  if i != 0 and i != 1 and i != 4:
    continue
  print("Month", (i + 1))
  prev = (start_time[i], 230)
  test_profit_original = 0.0
  
  month = str(i + 1)
  if i + 1 < 10:
    month = "0" + month
  save_file_name = "2018-" + month + "-original-test.log"
  
  original(cab_data[i], start_time[i], end_time[i], save_file_name)
  with open(save_file_name, "a+") as f:
    f.write(str(test_profit_original))
    f.write("\n")

Month 1
data loaded
Month 2
data loaded
Month 5
data loaded


In [0]:
print(test_profit_original)

20585.20999999981


In [0]:
test_profit_new = 0.0
prev_new = ("2018-01-01 00:00:00", 100)
# for i in range(265):
#   heappush(heap_new, ("2018-01-00 00:00:00", i + 1, i + 1)) 
# The first element is the last time drop off # The second element is the last time drop off location id and third element is the first time pick up id

In [0]:
fare = np.load("2018-fare.npy")
max_profit_id = np.argmax(fare, axis=1) + 1
max_profit = np.max(fare, axis=1)
print(max_profit_id)

[154 117   5  60  11  64 206 154 154   1  23  23 117 176   6 120  44 204
 117 154  99 156 117 184  31  45 117 108  67  64   1 172  86   6   1   1
  57  44  84   2 253 154 187 265 221 253 176 184 252  71 252  11 118  44
   1  27   1 251 187 253 184 154 206 206 156 154 184 253 251 154 206  23
 253 213  19 176 124  28 253 176 176  23  27 154 154 154 206 251 120 117
 156 156 204   5 156 204   9   1  19 156 109 108   1 176   1   1 154 221
   6  23 154 253 245 154 265 154   5 149 154 208   1   1  63 178  23 206
 124   1 154 201   1 156 176 115 251 258   5 117   1 122 154 123   1 175
   1   1  64 201 219 253 253 154 253  46   1 156 214 187   6 117   1 115
   1 253 154 156 184 222]


In [0]:
def new_algo_test(file, start, end, save_file_name):
  global prev_new, test_profit_new, max_profit_id
  df = pd.read_csv(file)
  print("data loaded")
  df = df[(df.tpep_pickup_datetime >= start) & (df.tpep_pickup_datetime < end)]
  df = df.sort_values(by=['tpep_pickup_datetime'])
  
  final_time = datetime.datetime.strptime(end, '%Y-%m-%d %H:%M:%S')
  with open(save_file_name, "a+") as f:
    while prev_new[0] < end:
      ele = prev_new
      f.write(str(ele))
      f.write(" ")
      f.write(str(test_profit_new))
      f.write("\n")
      t = datetime.datetime.strptime(ele[0], '%Y-%m-%d %H:%M:%S')
      weekday = t.weekday()
      day = t.day
      hour = t.hour
      row_idx = weekday * 24 + hour

      max_ids = set(np.argsort(-fare[row_idx])[:1] + 1)

      df_filter = df[(df.tpep_pickup_datetime > ele[0]) & (df.PULocationID.isin(max_ids))].reset_index()
      found = True
      j = 0
      if df_filter.shape[0] == 0:
  #       print("Category 1")
        found = False
      else:
  #       print("Category 2")
        new_t = datetime.datetime.strptime(df_filter.iloc[0]['tpep_pickup_datetime'], '%Y-%m-%d %H:%M:%S')
        new_weekday = new_t.weekday()
        new_day = new_t.day
        new_hour = new_t.hour
      while ((not found) or (new_hour != hour or new_day != day)) and (new_t < final_time):
  #       if not found:
  #         print("not found")
  #       elif new_day != day:
  #         print("day not match", "new_day", new_day, "day", day)
  #       elif new_hour != hour:
  #         print("hour not match", "hour", hour, "new_hour", new_hour)
  #       else:
  #         print("???")
        if day > 31:
          return
        j = 0
        hour += 1
        if hour == 24:
          hour = 0
          weekday += 1
          weekday %= 7
          day += 1
        row_idx = weekday * 24 + hour

        max_ids = set(np.argsort(-fare[row_idx])[:1] + 1)

        df_filter = df[(df.tpep_pickup_datetime > ele[0]) & (df.PULocationID.isin(max_ids))].reset_index()
        if df_filter.shape[0] == 0:
  #         print("Category 4")
          found = False
        else:
  #         print("Category 4")
          found = True
          for i in range(df_filter.shape[0]):
            new_t = datetime.datetime.strptime(df_filter.iloc[i]['tpep_pickup_datetime'], '%Y-%m-%d %H:%M:%S')
            new_weekday = new_t.weekday()
            new_day = new_t.day
            new_hour = new_t.hour
            if new_day < day or (new_day == day and new_hour < hour):
  #             print("Loop here")
              continue
            else:
              j = i
              break

      if (new_t >= final_time):
        break
      new_ele = (df_filter.iloc[j]['tpep_dropoff_datetime'], df_filter.iloc[j]['DOLocationID'])
      test_profit_new += float(df_filter.iloc[j]['total_amount'])
      prev_new = new_ele

In [0]:
for i in range(len(cab_data)):
  print("Month:", (i + 1))
  
  test_profit_new = 0.0
  prev_new = (start_time[i], 100)
  
  month = str(i + 1)
  if i + 1 < 10:
    month = "0" + month
  save_file_name = "2018-" + month + "-new-test.log"
  
  fare = np.load("2017-" + month + "-total-fare.npy")
  max_profit_id = np.argmax(fare, axis=1) + 1

  
  new_algo_test(cab_data[i], start_time[i], end_time[i], save_file_name)
  with open(save_file_name, "a+") as f:
    f.write(str(test_profit_new))
    f.write("\n")
  
#   new_algo_test(cab_data[i], start_time[i], end_time[i], save_file_name)

Month: 1
data loaded
Month: 2
data loaded
Month: 3
data loaded
Month: 4
data loaded
Month: 5
data loaded
Month: 6
data loaded
Month: 7
data loaded
Month: 8
data loaded
Month: 9
data loaded
Month: 10
data loaded
Month: 11
data loaded
Month: 12
data loaded
